Fix options rendering in APTConfigLine breaking its output
Without that added space, the line generated is actually invalid. Take
for instance Docker's apt repository: parsing its apt config line
`deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable`
will yield a well-formed repository. However, re-generating the line
with APTConfigLine from that Repository will yield
`deb [signed-by=/etc/apt/keyrings/docker.asc]https://download.docker.com/linux/debian bookworm stable`
(note the missing space). This will result in errors such as:
```
Error: Malformed entry 1 in list file /etc/apt/sources.list.d/stable.list ([option] not assignment)
Error: The list of sources could not be read.
```